# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = 'https://worldofgamelans.xyz/'
title = "World of Gamelans"
theme = 'book'
defaultContentLanguage = 'id'
enableRobotsTXT = true 

# Book configuration
disablePathToLower = true
enableGitInfo = true

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
    noClasses = true
    style = 'monokailight'
# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.id]
  languageName = 'Indonesian'
  contentDir = 'content'
  weight = 1

[menu]
# [[menu.before]]

[params]
  description = "Segala sesuatu tentang Gamelan Jawa"
  author = 'Bima Wiratama'

  BookTheme = 'light'
  BookToC = false
  # BookLogo = 'logo.png'
  # BookMenuBundle = '/menu'
  BookSection = 'gamelan'
  BookRepo = 'https://github.com/jikope/hugo-book'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main/exampleSite'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  BookServiceWorker = true
  BookTranslatedOnly = false
