#+TITLE: Perbedaan Srepeg Solo, Playon Jogja dan Playon Mataram
#+TYPE: post
#+DATE: <2021-12-30 Sat>
#+showthedate: show
#+DESCRIPTION: Pada masing-masing gaya karawitan surakarta maupun yogyakarta terdapat pola tabuhan gendhing dimana kenong memukul 1 kali setiap 1 angka balungan(nitir) dan kempul memukul 1 kali setiap 2 balungan. Pola gendhing ini disebut Srepeg pada karawitan Surakarta dan Playon pada karawitan Yogyakarta. 

Pada saat menonton pertunjukan wayang pasti sudah tidak asing bagi kita untuk mendengarkan musik iringan pada tiap adegan perang. Musik pengiring itu mempunyai nama yang berbeda-beda di setiap daerah jadi sering membuat bingung untuk khalayak umum yang belum pernah mengikuti grup karawitan.

Untuk gendhing yang mempunyai 1 tabuhan kenong untuk 1 balungan jika di gaya surakarta sering disebut dengan *srepeg* sedangkan di yogyakarta gendhing dengan struktur ini lebih sering disebut dengan *playon* atau *plajaran*. Srepeg sendiri mempunyai struktur gendhing lain di gaya karawitan yogyakarta yaitu 1 tabuhan kenong untuk 2 balungan. Pada gaya surakarta struktur gendhing 1 tabuhan kenon 1 balungan disebut dengan ayak-ayak tanggung.

Playon mataram seringkali disamakan dengan playon gaya yogyakarta padahal gendhing ini merupakan satu kesatuan gendhing tersendiri. Playon mataram mengacu pada gendhing di era kerajaan mataram islam, sebelum ada surakarta dan yogyakarta. Playon mataram ini ada dua versi yaitu pelog nem dan pelog barang. Pada era saat ini gendhing ini masih digunakan untuk mengiringi pertunjukkan wayang wong di kraton yogyakarta.
