#+TITLE: Uyon-Uyon Hadiluhung
#+TYPE: docs
#+DATE: <2022-01-14 Fri>
#+showthedate: show
#+CATEGORY: Instrumen Gamelan
#+DESCRIPTION:  Uyon-uyon hadiluhung merupakan acara rutin yang dilaksanakan di kraton yogyakarta setiap selapan (35 hari) sesuai dengan hari neptu sultan. Uyon-uyon hadiluhung digunakan untuk mencelebrasi weton waktu sultan lahir.

Uyon-uyon hadiluhung merupakan acara rutin yang dilaksanakan di kraton yogyakarta setiap selapan (35 hari) sesuai dengan hari neptu sultan. Uyon-uyon hadiluhung digunakan untuk mencelebrasi weton waktu sultan lahir.

Acara ini dimulai dengan gendhing kurmat dalem yaitu ~Prabu Mataram Slendro 9~ dan ~Raja Manggala Pelog 6~. Gendhing ini digunakan untuk memuji sultan yang sedang bertahta. Lalu setelah gendhing pertama akan diperdengarkan sebuah gendhing soran. Gendhing soran ini gendhing yang tidak memakai instrumen alusan dan ditabuh dengan cara soran yaitu volume yang keras. 

Pada gendhing nomor 3 akan diperdengarkan gendhing iringan beksan. Bisa beksan srimpi, bedhaya atau gagahan. Gendhing beksan biasanya akan dimulai dari lagon lalu kandha lalu gendhing utama lalu lagon penutup. Untuk pemilihan laras gendhing biasanya akan bergantian dari gendhing pembuka ke gendhing selanjutnya.

Lalu ada 3 gendhing alusan yang disajikan untuk gendhing pertama dari ketiga gendhing terakhir biasanya menggunakan pathet 6 atau 6 pada pelog. Untuk gendhing nomor 2 memakai pathet 9 atau 5 pada pelog. Lalu untuk gendhing nomor 3 memakai pathet manyura atau barang pada pelog.
