name: Master
on:
    push:
    branches:
	- master
jobs:
    build:
	name: Build hugo
	steps:
	    - uses: actions/checkout@v2
	    with:
		submodules: true
	    - name: Setup Hugo
	    uses: peaceiris/actions-hugo@v2
	    with:
		hugo-version: '0.88.1'
	    - name: Build
	    run: hugo --minify
	    - name: Upload public directory
	    uses: actions/upload-artifact@v2
	    if: github.ref = 'refs/heads/master'
	    with:
		name: public
		path: public/
	    retention-days: 1

deploy:
  name: Deploy to Netlify
  needs: build
  runs-on:  ubuntu-18.04
  steps:
    - name: Download public directory
      uses: actions/download-artifact@v2
      with:
        name: public
        path: public/
    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy -p --dir=public
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
